/* Generated by vlGui tool v0.1.0
 * Size: 8 x 8
 * Image's name: vlGui_bitmapShirop
 * Driver: ssd1306
 */
#ifndef _VLGUI_BITMAPSHIROP_H_
#define _VLGUI_BITMAPSHIROP_H_

const unsigned char vlGui_bitmapShirop[] = {
    0x18, 0x66, 0x81, 0xa5, 0x81, 0x99, 0x7e, 0x81, 
};

#endif // _VLGUI_BITMAPSHIROP_H_