# @file fontsGen.py
# @author Weilong Shen (valonshen@foxmail.com)
# @brief
# @version 0.1
# @date 2022-07-26
#
# Copyright © 2021 - 2022 Weilong Shen (valonshen@foxmail.com)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import argparse
import pygame
from PIL import Image

parse = argparse.ArgumentParser()
parse.add_argument("-s", "--size", type=int, default=16, help="Set size of font")
parse.add_argument("-e", "--encode", default='utf-8', choices=['utf-8', 'gb2312'], help="Select encoding format")
parse.add_argument("-c", "--config", default="None", help="configure file name")
parse.add_argument("-f", "--font", default="None", help="select font")
parse.add_argument("-l", "--list", action='store_true', help="list all of supported fonts")
parse.add_argument("-b", "--bold", action='store_true', help="Bold")
parse.add_argument("-r", "--review", action='store_true', help="don't generate file. Show generated demo")

codeRange = ['b0a1-b0fe', 'b1a1-b1fe', 'b2a1-b2fe', 'b3a1-b3fe', 'b4a1-b4fe', 'b5a1-b5fe', 'b6a1-b6fe', 'b7a1-b7fe',
             'b8a1-b8fe', 'b9a1-b9fe',
             'baa1-bafe', 'bba1-bbfe', 'bca1-bcfe', 'bda1-bdfe', 'bea1-befe', 'bfa1-bffe', 'c0a1-c0fe', 'c1a1-c1fe',
             'c2a1-c2fe', 'c3a1-c3fe',
             'c4a1-c4fe', 'c5a1-c5fe', 'c6a1-c6fe', 'c7a1-c7fe', 'c8a1-c8fe', 'c9a1-c9fe', 'caa1-cafe', 'cba1-cbfe',
             'cca1-ccfe', 'cda1-cdfe',
             'cea1-cefe', 'cfa1-cffe', 'd0a1-d0fe', 'd1a1-d1fe', 'd2a1-d2fe', 'd3a1-d3fe', 'd4a1-d4fe', 'd5a1-d5fe',
             'd6a1-d6fe', 'd7a1-d7f9',
             ]

class TableItem:
    end = 0
    num = 0
    pattern = []

    def __init__(self, max):
        self.end = max

    def getPatternLength(self):
        return self.num

    def appendPattern(self, m):
        self.pattern.append(m)
        self.num = self.num + 1


def getFontMap(font, text):
    # 渲染图片，设置背景颜色和字体样式,前面的颜色是字体颜色
    ftext = font.render(text, False, (0, 0, 0), (255, 255, 255))
    # 保存图片
    fontMap = pygame.image.tostring(ftext, 'P')
    return fontMap
    # pygame.image.save(ftext, "image.jpg")  # 图片保存地址

def showFontDemo(font, text):
    ftext = font.render(text, False, (0, 0, 0), (255, 255, 255))
    pygame.image.save(ftext, "image.jpg")  # 图片保存地址

def mapToArray(map):
    array = []
    v = 0
    c = 0
    for p in map:
        v = v << 1
        if p != 0:
            v = v + 1
        c = c + 1
        if c >= 8:
            array.append(v)
            v = 0
            c = 0
    if c != 0:
        array.append(v)
    return array

def save(file, table):
    with open(file, 'w', encoding="utf-8") as f:
        incDefine = "_" + str(file).split('.')[0].upper() + "_H_"
        f.writelines("/* Generated by vlonGui tool v0.0.1\n")
        f.writelines(" */\n")
        f.writelines("#ifndef " + incDefine + "\n")
        f.writelines("#define " + incDefine + "\n\n")
        f.writelines("const unsigned char " + str(file).split('.')[0] + "[] = {\n")

        f.write(hex(args.size & 0xff) + ',\t//the width of font\n')
        f.write(hex(len(table) & 0xff) + ", ")
        f.write(hex((len(table) >> 8) & 0xff) + ",\t //table length\n")
        for item in table:
            f.write(hex(item.end & 0xff) + ', ')
            f.write(hex((item.end >> 8) & 0xff) + ', ')
            f.write(hex(item.getPatternLength() & 0xff) + ', ')
            f.write(hex((item.getPatternLength() >> 8) & 0xff) + ',\t//the ending of this segment, the length of this segment\n')

        for item in table:
            for array in item.pattern:
                for v in array:
                    f.write(hex(v) + ', ')
                f.write('\n')

        f.writelines("\;\n\n#endif // " + incDefine)

if __name__ == '__main__':
    table = []

    args = parse.parse_args()
    # print all of supported fronts. Then exit.
    if args.list:
        fontsList = pygame.font.get_fonts()
        print("Support fonts:")
        for font in fontsList:
            print("\t" + font)
        exit(0)

    # pygame初始化
    pygame.init()
    if args.font == 'None':
        selectedFont = pygame.font.get_default_font()
    elif pygame.font.match_font(args.font):
        selectedFont = args.font
    else:
        print("Don't support this font : " + args.font)
        exit(-1)
    print("Selected font is : " + selectedFont)

    font = pygame.font.SysFont('./dick.ttf', args.size, args.bold)

    if (args.review):
        showFontDemo(font, "VlonGui 蓝牙连接")
        exit(0)

    for entry in codeRange:
        print(entry)
        r = entry.split('-')
        min = int(r[0], 16)
        max = int(r[1], 16)

        item = TableItem(max)
        table.append(item)

        for value in range(min, max + 1):
            # 待转换文字
            code = value.to_bytes(2, 'big')
            text = code.decode(args.encode)
            map = getFontMap(font, text)
            item.appendPattern(mapToArray(map))

    save(selectedFont + '_' + str(args.size) + "_" + args.encode + '.c', table)
    print('done!!!')
