/* Generated by vlGui tool v0.1.0
 * Size: 6 x 7
 * Image's name: vlGui_bmpFoodEmpty
 * Driver: ssd1306
 */
#ifndef _VLGUI_BMPFOODEMPTY_H_
#define _VLGUI_BMPFOODEMPTY_H_

const unsigned char vlGui_bmpFoodEmpty[] = {
    0x06, 0x00, 0x07, 0x00, 
    0x14, 0x20, 0x04, 0x12, 0x00, 0x09, 0x0c, 
};

#endif // _VLGUI_BMPFOODEMPTY_H_