/* Generated by vlGui tool v0.1.0
 * Size: 7 x 8
 * Image's name: vlGui_bmpEducation
 * Driver: ssd1306
 */
#ifndef _VLGUI_BMPEDUCATION_H_
#define _VLGUI_BMPEDUCATION_H_

const unsigned char vlGui_bmpEducation[] = {
    0x07, 0x00, 0x08, 0x00, 
    0x00, 0x27, 0x27, 0x3f, 0x3f, 0x3f, 0x01, 0x3f, 
};

#endif // _VLGUI_BMPEDUCATION_H_