/* Generated by vlGui tool v0.1.0
 * Size: 6 x 7
 * Image's name: vlGui_bmpBlood
 * Driver: ssd1306
 */
#ifndef _VLGUI_BMPBLOOD_H_
#define _VLGUI_BMPBLOOD_H_

const unsigned char vlGui_bmpBlood[] = {
    0x06, 0x00, 0x07, 0x00, 
    0x04, 0x0e, 0x1f, 0x1f, 0x1d, 0x1b, 0x0e, 
};

#endif // _VLGUI_BMPBLOOD_H_