/* Generated by vlGui tool v0.1.0
 * Size: 6 x 7
 * Image's name: vlGui_bmpBloodEmpty
 * Driver: ssd1306
 */
#ifndef _VLGUI_BMPBLOODEMPTY_H_
#define _VLGUI_BMPBLOODEMPTY_H_

const unsigned char vlGui_bmpBloodEmpty[] = {
    0x06, 0x00, 0x07, 0x00, 
    0x04, 0x0a, 0x00, 0x11, 0x00, 0x11, 0x0a, 
};

#endif // _VLGUI_BMPBLOODEMPTY_H_