/* Generated by vlGui tool v0.1.0
 * Size: 6 x 7
 * Image's name: vlGui_bmpFood
 * Driver: ssd1306
 */
#ifndef _VLGUI_BMPFOOD_H_
#define _VLGUI_BMPFOOD_H_

const unsigned char vlGui_bmpFood[] = {
    0x06, 0x00, 0x07, 0x00, 0x18, 0x38, 0x38, 0x1c, 0x0f, 0x0f, 0x0c,
};

#endif // _VLGUI_BMPFOOD_H_