/* Generated by vlGui tool v0.1.0
 * Size: 7 x 8
 * Image's name: vlGui_bmpEducationEmpty
 * Driver: ssd1306
 */
#ifndef _VLGUI_BMPEDUCATIONEMPTY_H_
#define _VLGUI_BMPEDUCATIONEMPTY_H_

const unsigned char vlGui_bmpEducationEmpty[] = {
    0x07, 0x00, 0x08, 0x00, 
    0x00, 0x2b, 0x00, 0x21, 0x01, 0x21, 0x00, 0x2b, 
};

#endif // _VLGUI_BMPEDUCATIONEMPTY_H_