/* Generated by vlGui tool v0.1.0
 * Size: 6 x 7
 * Image's name: vlGui_bmpHeartEmpty
 * Driver: ssd1306
 */
#ifndef _VLGUI_BMPHEARTEMPTY_H_
#define _VLGUI_BMPHEARTEMPTY_H_

const unsigned char vlGui_bmpHeartEmpty[] = {
    0x06, 0x00, 0x07, 0x00, 0x00, 0x12, 0x2d, 0x21, 0x12, 0x0c, 0x00,
};

#endif // _VLGUI_BMPHEARTEMPTY_H_