/* Generated by vlGui tool v0.1.0
 * Size: 6 x 7
 * Image's name: vlGui_bmpHeart
 * Driver: ssd1306
 */
#ifndef _VLGUI_BMPHEART_H_
#define _VLGUI_BMPHEART_H_

const unsigned char vlGui_bmpHeart[] = {
    0x06, 0x00, 0x07, 0x00, 0x00, 0x12, 0x3f, 0x3f, 0x1e, 0x0c, 0x00,
};

#endif // _VLGUI_BMPHEART_H_